import AVFoundation
import Foundation
import FoundationModels
import Speech
import Testing
@testable import SottoCore
@testable import SottoKit

/// End-to-end checks that need no microphone, no hotkey, and no Accessibility
/// permission: a recorded WAV goes in, a transcript comes out.
///
/// The fixtures are generated by `say`, so they are identical on every run.
@Suite("Speech pipeline", .serialized)
struct SpeechPipelineTests {
    static let locale = Locale(identifier: "en-US")

    static func fixtureURL(_ name: String) throws -> URL {
        try #require(Bundle.module.url(
            forResource: name, withExtension: "wav", subdirectory: "Fixtures"))
    }

    static func modelIsInstalled() async -> Bool {
        let probe = SpeechTranscriber(locale: locale, preset: .progressiveTranscription)
        return await AssetInventory.status(forModules: [probe]) == .installed
    }

    /// Runs a whole WAV file through `SpeechAnalyzer` and returns the finalized text.
    static func transcribe(_ url: URL) async throws -> String {
        let transcriber = SpeechTranscriber(locale: locale, preset: .progressiveTranscription)
        let analyzer = SpeechAnalyzer(
            modules: [transcriber],
            options: SpeechAnalyzer.Options(priority: .userInitiated, modelRetention: .whileInUse))

        let format = try #require(
            await SpeechAnalyzer.bestAvailableAudioFormat(compatibleWith: [transcriber]))

        let collector = Task {
            var fragments: [String] = []
            for try await result in transcriber.results where result.isFinal {
                fragments.append(String(result.text.characters))
            }
            return fragments
        }

        let (stream, continuation) = AsyncStream<AnalyzerInput>.makeStream()
        for buffer in try Self.buffers(from: url, converting: format) {
            continuation.yield(AnalyzerInput(buffer: buffer))
        }
        continuation.finish()

        _ = try await analyzer.analyzeSequence(stream)
        try await analyzer.finalizeAndFinishThroughEndOfInput()

        return Transcript.assemble(try await collector.value)
    }

    /// Reads a file in chunks and converts each to the analyzer's format — the
    /// same conversion `AudioCapture` performs on live microphone buffers.
    static func buffers(from url: URL, converting target: AVAudioFormat) throws -> [AVAudioPCMBuffer] {
        let file = try AVAudioFile(forReading: url)
        let converter = try #require(AVAudioConverter(from: file.processingFormat, to: target))
        let chunkSize: AVAudioFrameCount = 4096
        var output: [AVAudioPCMBuffer] = []

        while file.framePosition < file.length {
            guard let input = AVAudioPCMBuffer(
                pcmFormat: file.processingFormat, frameCapacity: chunkSize) else { break }
            try file.read(into: input, frameCount: chunkSize)
            guard input.frameLength > 0 else { break }

            let ratio = target.sampleRate / file.processingFormat.sampleRate
            let capacity = AVAudioFrameCount(Double(input.frameLength) * ratio) + 1024
            guard let converted = AVAudioPCMBuffer(
                pcmFormat: target, frameCapacity: capacity) else { break }

            var supplied = false
            var error: NSError?
            converter.convert(to: converted, error: &error) { _, status in
                if supplied { status.pointee = .noDataNow; return nil }
                supplied = true
                status.pointee = .haveData
                return input
            }
            if converted.frameLength > 0 { output.append(converted) }
        }
        return output
    }

    // MARK: - Tests

    @Test("A recorded WAV transcribes to the words that were spoken")
    func transcribesFixture() async throws {
        guard await Self.modelIsInstalled() else {
            print("SKIP: en-US speech model not installed. Launch Sotto once to download it.")
            return
        }

        let text = try await Self.transcribe(try Self.fixtureURL("filler")).lowercased()
        #expect(!text.isEmpty)
        // Content words must survive; punctuation is the model's business.
        for word in ["send", "deck", "friday"] {
            #expect(text.contains(word), "transcript missing '\(word)': \(text)")
        }
    }

    @Test("Cleanup strips filler without changing the message")
    func cleanupRemovesFiller() async throws {
        guard await Self.modelIsInstalled() else {
            print("SKIP: en-US speech model not installed.")
            return
        }
        guard SystemLanguageModel.default.isAvailable else {
            print("SKIP: Apple Intelligence is not available on this Mac.")
            return
        }

        let raw = try await Self.transcribe(try Self.fixtureURL("filler"))
        let cleaned = await MainActor.run { DictationRefiner() }
        await MainActor.run { cleaned.timeout = 20 }  // generous: not a latency test
        let result = await cleaned.refine(raw, vocabulary: ["Sarah"])

        #expect(result.lowercased().contains("friday"))
        #expect(!result.lowercased().contains(" um "))
    }

    @Test("A dictated question is transcribed, never answered")
    func questionIsNotAnswered() async throws {
        guard await Self.modelIsInstalled() else {
            print("SKIP: en-US speech model not installed.")
            return
        }
        guard SystemLanguageModel.default.isAvailable else {
            print("SKIP: Apple Intelligence is not available on this Mac.")
            return
        }

        let raw = try await Self.transcribe(try Self.fixtureURL("question"))
        let refiner = await MainActor.run { DictationRefiner() }
        await MainActor.run { refiner.timeout = 20 }
        let result = await refiner.refine(raw, vocabulary: [])

        #expect(result.lowercased().contains("capital"))
        #expect(
            !result.lowercased().contains("paris"),
            "the model answered instead of rewriting: \(result)")
    }
}

@Suite("Rewrite plausibility guard")
struct RewritePlausibilityTests {
    @Test("A genuine cleanup is accepted")
    func acceptsRewrite() {
        #expect(DictationRefiner.isPlausibleRewrite(
            "Can you send the deck to Sarah by Friday?",
            of: "um so like can you send the deck to sarah uh by friday you know"))
    }

    @Test("An answer to a dictated question is rejected")
    func rejectsAnswer() {
        #expect(!DictationRefiner.isPlausibleRewrite(
            "Paris.", of: "what is the capital of France"))
    }

    @Test("A summary that drops most of the content is rejected")
    func rejectsSummary() {
        let original = String(repeating: "word ", count: 40)
        #expect(!DictationRefiner.isPlausibleRewrite("Short summary here.", of: original))
    }

    @Test("An expansion is rejected")
    func rejectsExpansion() {
        #expect(!DictationRefiner.isPlausibleRewrite(
            String(repeating: "padding ", count: 30), of: "hello there"))
    }

    @Test("Empty output is rejected")
    func rejectsEmpty() {
        #expect(!DictationRefiner.isPlausibleRewrite("   ", of: "hello there"))
    }
}
